//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSH.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSH.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon AppIco {
            get {
                object obj = ResourceManager.GetObject("AppIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap archive {
            get {
                object obj = ResourceManager.GetObject("archive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_bold_circle_outline {
            get {
                object obj = ResourceManager.GetObject("arrow_left_bold_circle_outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_bold_circle_outline_off {
            get {
                object obj = ResourceManager.GetObject("arrow_left_bold_circle_outline_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_circle_fill {
            get {
                object obj = ResourceManager.GetObject("arrow_left_circle_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_circle_line {
            get {
                object obj = ResourceManager.GetObject("arrow_left_circle_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_circle_line_off {
            get {
                object obj = ResourceManager.GetObject("arrow_left_circle_line_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_circle_line_on {
            get {
                object obj = ResourceManager.GetObject("arrow_left_circle_line_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherung vom  ähnelt.
        /// </summary>
        internal static string BACKUP_FROM_DATE {
            get {
                return ResourceManager.GetString("BACKUP_FROM_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backup_restore {
            get {
                object obj = ResourceManager.GetObject("backup_restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backup_service_client_32 {
            get {
                object obj = ResourceManager.GetObject("backup_service_client_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatisches Backup ähnelt.
        /// </summary>
        internal static string BACKUP_TITLE_AUTOMATIC {
            get {
                return ResourceManager.GetString("BACKUP_TITLE_AUTOMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manuelle Sicherung ähnelt.
        /// </summary>
        internal static string BACKUP_TITLE_MANUAL {
            get {
                return ResourceManager.GetString("BACKUP_TITLE_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ist derzeit unbekannt. ähnelt.
        /// </summary>
        internal static string BackupStatus_ {
            get {
                return ResourceManager.GetString("BackupStatus_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Service Home wird ordnungsgemäß ausgeführt. ähnelt.
        /// </summary>
        internal static string BackupStatus_0 {
            get {
                return ResourceManager.GetString("BackupStatus_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensicherung läuft... ähnelt.
        /// </summary>
        internal static string BackupStatus_1 {
            get {
                return ResourceManager.GetString("BackupStatus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Datensicherung wurde nicht korrekt abgeschlossen. ähnelt.
        /// </summary>
        internal static string BackupStatus_2 {
            get {
                return ResourceManager.GetString("BackupStatus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batteriebetrieb. Es werden keine Sicherungen durchgeführt. ähnelt.
        /// </summary>
        internal static string BackupStatus_3 {
            get {
                return ResourceManager.GetString("BackupStatus_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatische Sicherung ist deaktivert. ähnelt.
        /// </summary>
        internal static string BackupStatus_4 {
            get {
                return ResourceManager.GetString("BackupStatus_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox_blank_circle_line {
            get {
                object obj = ResourceManager.GetObject("checkbox_blank_circle_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox_circle_line {
            get {
                object obj = ResourceManager.GetObject("checkbox_circle_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_circle_fill {
            get {
                object obj = ResourceManager.GetObject("close_circle_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_circle_line {
            get {
                object obj = ResourceManager.GetObject("close_circle_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backupbrowser ähnelt.
        /// </summary>
        internal static string CONTEXT_MENU_BACKUP_BROWSER_WINDOW {
            get {
                return ResourceManager.GetString("CONTEXT_MENU_BACKUP_BROWSER_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manuelle Sicherung starten ähnelt.
        /// </summary>
        internal static string CONTEXT_MENU_BACKUP_START {
            get {
                return ResourceManager.GetString("CONTEXT_MENU_BACKUP_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manuelle Sicherung starten (+ Optionen) ähnelt.
        /// </summary>
        internal static string CONTEXT_MENU_BACKUP_START_OPTIONS {
            get {
                return ResourceManager.GetString("CONTEXT_MENU_BACKUP_START_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Service Home beenden ähnelt.
        /// </summary>
        internal static string CONTEXT_MENU_CLOSE_APP {
            get {
                return ResourceManager.GetString("CONTEXT_MENU_CLOSE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status und Konfigurieren ähnelt.
        /// </summary>
        internal static string CONTEXT_MENU_STATUS_WINDOW {
            get {
                return ResourceManager.GetString("CONTEXT_MENU_STATUS_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dashminus {
            get {
                object obj = ResourceManager.GetObject("dashminus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dashplus {
            get {
                object obj = ResourceManager.GetObject("dashplus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_bin_line {
            get {
                object obj = ResourceManager.GetObject("delete_bin_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;Täglich um&apos; HH:mm:ss ähnelt.
        /// </summary>
        internal static string DLG_ADD_SCHEDULE_FORMAT_DAILY {
            get {
                return ResourceManager.GetString("DLG_ADD_SCHEDULE.FORMAT.DAILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;Stündlich, immer in Minute&apos; mm ähnelt.
        /// </summary>
        internal static string DLG_ADD_SCHEDULE_FORMAT_HOURLY {
            get {
                return ResourceManager.GetString("DLG_ADD_SCHEDULE.FORMAT.HOURLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;Jeden&apos; dd. &apos;im Monat&apos;, &apos;um&apos; HH:mm:ss ähnelt.
        /// </summary>
        internal static string DLG_ADD_SCHEDULE_FORMAT_MONTHLY {
            get {
                return ResourceManager.GetString("DLG_ADD_SCHEDULE.FORMAT.MONTHLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;Einmalig am&apos; dd.MM.yyyy &apos;um&apos; HH:mm:ss ähnelt.
        /// </summary>
        internal static string DLG_ADD_SCHEDULE_FORMAT_ONCE {
            get {
                return ResourceManager.GetString("DLG_ADD_SCHEDULE.FORMAT.ONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;Jeden&apos; dddd, &apos;um&apos; HH:mm:ss ähnelt.
        /// </summary>
        internal static string DLG_ADD_SCHEDULE_FORMAT_WEEKLY {
            get {
                return ResourceManager.GetString("DLG_ADD_SCHEDULE.FORMAT.WEEKLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error_warning_line {
            get {
                object obj = ResourceManager.GetObject("error_warning_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye {
            get {
                object obj = ResourceManager.GetObject("eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_line {
            get {
                object obj = ResourceManager.GetObject("eye_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favorite {
            get {
                object obj = ResourceManager.GetObject("favorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_copy_2_fill {
            get {
                object obj = ResourceManager.GetObject("file_copy_2_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_copy_2_line {
            get {
                object obj = ResourceManager.GetObject("file_copy_2_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_16 {
            get {
                object obj = ResourceManager.GetObject("folder_open_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap function_line {
            get {
                object obj = ResourceManager.GetObject("function_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hintergrund_Menu_oben {
            get {
                object obj = ResourceManager.GetObject("Hintergrund_Menu_oben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_4_line {
            get {
                object obj = ResourceManager.GetObject("home_4_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre letzte Datensicherung liegt bereits {0} Tage zurück. Führen Sie eine Datensicherung aus, damit Ihre aktuellen Dateien gesichert sind. ähnelt.
        /// </summary>
        internal static string INFO_BACKUP_OLD_TEXT {
            get {
                return ResourceManager.GetString("INFO_BACKUP_OLD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensicherung veraltet ähnelt.
        /// </summary>
        internal static string INFO_BACKUP_OLD_TITLE {
            get {
                return ResourceManager.GetString("INFO_BACKUP_OLD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die geplante Sicherung wurde erfolgreich abgeschlossen. ähnelt.
        /// </summary>
        internal static string INFO_BACKUP_SUCCESSFUL_TEXT {
            get {
                return ResourceManager.GetString("INFO_BACKUP_SUCCESSFUL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensicherung erfolgreich ähnelt.
        /// </summary>
        internal static string INFO_BACKUP_SUCCESSFUL_TITLE {
            get {
                return ResourceManager.GetString("INFO_BACKUP_SUCCESSFUL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die geplante Datensicherung wurde mit Problemen beendet. Klicken Sie hier für mehr Informationen. ähnelt.
        /// </summary>
        internal static string INFO_BACKUP_UNSUCCESSFUL_TEXT {
            get {
                return ResourceManager.GetString("INFO_BACKUP_UNSUCCESSFUL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensicherung mit Problemen beendet ähnelt.
        /// </summary>
        internal static string INFO_BACKUP_UNSUCCESSFUL_TITLE {
            get {
                return ResourceManager.GetString("INFO_BACKUP_UNSUCCESSFUL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Service Home 3 ist noch nicht konfiguriert und sichert daher noch keine Daten.\r\n\r\nDoppelklicken Sie hier, um die Konfiguration zu starten. ähnelt.
        /// </summary>
        internal static string INFO_BSH_NOT_CONFIGURED_TEXT {
            get {
                return ResourceManager.GetString("INFO_BSH_NOT_CONFIGURED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht konfiguriert. ähnelt.
        /// </summary>
        internal static string INFO_BSH_NOT_CONFIGURED_TITLE {
            get {
                return ResourceManager.GetString("INFO_BSH_NOT_CONFIGURED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf dem Backupmedium ist nicht mehr genug Speicherplatz vorhanden. Löschen Sie Datensicherungen oder wechseln Sie das Medium. ähnelt.
        /// </summary>
        internal static string INFO_NO_DISKSPACE_LEFT_TEXT {
            get {
                return ResourceManager.GetString("INFO_NO_DISKSPACE_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht genug Speicherplatz. ähnelt.
        /// </summary>
        internal static string INFO_NO_DISKSPACE_LEFT_TITLE {
            get {
                return ResourceManager.GetString("INFO_NO_DISKSPACE_LEFT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keyboard_backspace {
            get {
                object obj = ResourceManager.GetObject("keyboard_backspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungsdatum:  ähnelt.
        /// </summary>
        internal static string LBL_CHANGE_DATE {
            get {
                return ResourceManager.GetString("LBL_CHANGE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größe:  ähnelt.
        /// </summary>
        internal static string LBL_SIZE {
            get {
                return ResourceManager.GetString("LBL_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu_fill {
            get {
                object obj = ResourceManager.GetObject("menu_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu_fill1 {
            get {
                object obj = ResourceManager.GetObject("menu_fill1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap moreinfo_backgr {
            get {
                object obj = ResourceManager.GetObject("moreinfo_backgr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Sicherungsmedium steht aktuell nicht zur Verfügung, weshalb die Sicherung abgebrochen wird. ähnelt.
        /// </summary>
        internal static string MSG_BACKUP_DEVICE_NOT_READY_TEXT {
            get {
                return ResourceManager.GetString("MSG_BACKUP_DEVICE_NOT_READY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherungsmedium nicht bereit ähnelt.
        /// </summary>
        internal static string MSG_BACKUP_DEVICE_NOT_READY_TITLE {
            get {
                return ResourceManager.GetString("MSG_BACKUP_DEVICE_NOT_READY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das angegebene Kennwort ist falsch. ähnelt.
        /// </summary>
        internal static string MSG_PASSWORD_WRONG_TEXT {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_WRONG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kennwort falsch ähnelt.
        /// </summary>
        internal static string MSG_PASSWORD_WRONG_TITLE {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_WRONG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine andere Sicherungsaufgabe wird aktuell bereits ausgeführt, weshalb diese Sicherung abgebrochen wird. ähnelt.
        /// </summary>
        internal static string MSG_TASK_RUNNING_TEXT {
            get {
                return ResourceManager.GetString("MSG_TASK_RUNNING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Andere Sicherungsaufgabe in Bearbeitung ähnelt.
        /// </summary>
        internal static string MSG_TASK_RUNNING_TITLE {
            get {
                return ResourceManager.GetString("MSG_TASK_RUNNING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil_box_outline {
            get {
                object obj = ResourceManager.GetObject("pencil_box_outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_circle_outline_gray {
            get {
                object obj = ResourceManager.GetObject("play_circle_outline_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_line {
            get {
                object obj = ResourceManager.GetObject("question_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_line {
            get {
                object obj = ResourceManager.GetObject("search_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_3_fill {
            get {
                object obj = ResourceManager.GetObject("settings_3_fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_3_line {
            get {
                object obj = ResourceManager.GetObject("settings_3_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap status_error {
            get {
                object obj = ResourceManager.GetObject("status_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap status_ok {
            get {
                object obj = ResourceManager.GetObject("status_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon status_red {
            get {
                object obj = ResourceManager.GetObject("status_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon status_refresh {
            get {
                object obj = ResourceManager.GetObject("status_refresh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap status_running {
            get {
                object obj = ResourceManager.GetObject("status_running", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap system_installer {
            get {
                object obj = ResourceManager.GetObject("system_installer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap system_lock_screen {
            get {
                object obj = ResourceManager.GetObject("system_lock_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_2 {
            get {
                object obj = ResourceManager.GetObject("table_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Service Home 3 fährt den Computer nach einer erfolgreichen Aktion herunter... ähnelt.
        /// </summary>
        internal static string TASK_BSH_SHUTDOWN_PC {
            get {
                return ResourceManager.GetString("TASK_BSH_SHUTDOWN_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap taskdialog_bg {
            get {
                object obj = ResourceManager.GetObject("taskdialog_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap taskdialog_hover {
            get {
                object obj = ResourceManager.GetObject("taskdialog_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toggle_off {
            get {
                object obj = ResourceManager.GetObject("toggle_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toggle_on {
            get {
                object obj = ResourceManager.GetObject("toggle_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topbackground {
            get {
                object obj = ResourceManager.GetObject("topbackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topBgrLine1 {
            get {
                object obj = ResourceManager.GetObject("topBgrLine1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topBgrLine2 {
            get {
                object obj = ResourceManager.GetObject("topBgrLine2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topBgrLine3 {
            get {
                object obj = ResourceManager.GetObject("topBgrLine3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topbrowser {
            get {
                object obj = ResourceManager.GetObject("topbrowser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topPassword {
            get {
                object obj = ResourceManager.GetObject("topPassword", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Service Home wartet auf das Datensicherungsmedium,  ähnelt.
        /// </summary>
        internal static string WAIT_0 {
            get {
                return ResourceManager.GetString("WAIT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Service Home wartet auf das Datensicherungsmedium, ähnelt.
        /// </summary>
        internal static string WAIT_1 {
            get {
                return ResourceManager.GetString("WAIT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Service Home wartet auf das Datensicherungsmedium, ähnelt.
        /// </summary>
        internal static string WAIT_2 {
            get {
                return ResourceManager.GetString("WAIT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Service Home wartet auf das Datensicherungsmedium,  ähnelt.
        /// </summary>
        internal static string WAIT_3 {
            get {
                return ResourceManager.GetString("WAIT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügen Sie nun die Verzeichnisse der Liste hinzu, die gesichert werden sollen. ähnelt.
        /// </summary>
        internal static string WELCOME_STEP_1 {
            get {
                return ResourceManager.GetString("WELCOME_STEP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie nun den Datenträger aus, auf dem die Datensicherung gespeichert werden soll. Alternativ können Sie die Datensicherung auf einem FTP-Server speichern. ähnelt.
        /// </summary>
        internal static string WELCOME_STEP_2 {
            get {
                return ResourceManager.GetString("WELCOME_STEP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nun können Sie entscheiden, ob Backup Service Home alle Einstellungen automatisch festlegt oder ob Sie die Einstellungen manuell vornehmen möchten. ähnelt.
        /// </summary>
        internal static string WELCOME_STEP_3 {
            get {
                return ResourceManager.GetString("WELCOME_STEP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einen Moment bitte... ähnelt.
        /// </summary>
        internal static string WELCOME_STEP_4 {
            get {
                return ResourceManager.GetString("WELCOME_STEP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie nun das Backupmedium aus, auf dem die zu importierenden Sicherungen liegen. ähnelt.
        /// </summary>
        internal static string WELCOME_STEP_5 {
            get {
                return ResourceManager.GetString("WELCOME_STEP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie nun die Sicherung aus, die Sie importieren möchten. ähnelt.
        /// </summary>
        internal static string WELCOME_STEP_6 {
            get {
                return ResourceManager.GetString("WELCOME_STEP_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legen Sie nun fest, welches Verzeichnis welcher Sicherung zugeordnet werden soll. ähnelt.
        /// </summary>
        internal static string WELCOME_STEP_7 {
            get {
                return ResourceManager.GetString("WELCOME_STEP_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welche Daten möchten Sie sichern? ähnelt.
        /// </summary>
        internal static string WELCOMETITLE_STEP_1 {
            get {
                return ResourceManager.GetString("WELCOMETITLE_STEP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wo möchten Sie Ihre Sicherungen ablegen? ähnelt.
        /// </summary>
        internal static string WELCOMETITLE_STEP_2 {
            get {
                return ResourceManager.GetString("WELCOMETITLE_STEP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen Sie den Sicherungstyp aus. ähnelt.
        /// </summary>
        internal static string WELCOMETITLE_STEP_3 {
            get {
                return ResourceManager.GetString("WELCOMETITLE_STEP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Service Home wird konfiguriert... ähnelt.
        /// </summary>
        internal static string WELCOMETITLE_STEP_4 {
            get {
                return ResourceManager.GetString("WELCOMETITLE_STEP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Von welchem Medium möchten Sie Sicherungen importieren? ähnelt.
        /// </summary>
        internal static string WELCOMETITLE_STEP_5 {
            get {
                return ResourceManager.GetString("WELCOMETITLE_STEP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherung auswählen. ähnelt.
        /// </summary>
        internal static string WELCOMETITLE_STEP_6 {
            get {
                return ResourceManager.GetString("WELCOMETITLE_STEP_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherungen der lokalen Dateistruktur anpassen. ähnelt.
        /// </summary>
        internal static string WELCOMETITLE_STEP_7 {
            get {
                return ResourceManager.GetString("WELCOMETITLE_STEP_7", resourceCulture);
            }
        }
    }
}
