//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brightbits.BSH.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brightbits.BSH.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateien werden gesichert... ähnelt.
        /// </summary>
        internal static string STATUS_BACKUP_COPY_SHORT {
            get {
                return ResourceManager.GetString("STATUS_BACKUP_COPY_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Dateien werden auf dem Backupmedium gesichert... ähnelt.
        /// </summary>
        internal static string STATUS_BACKUP_COPY_TEXT {
            get {
                return ResourceManager.GetString("STATUS_BACKUP_COPY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherung abschließen... ähnelt.
        /// </summary>
        internal static string STATUS_BACKUP_FINISHED_SHORT {
            get {
                return ResourceManager.GetString("STATUS_BACKUP_FINISHED_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Sicherung wird nun abgeschlossen... ähnelt.
        /// </summary>
        internal static string STATUS_BACKUP_FINISHED_TEXT {
            get {
                return ResourceManager.GetString("STATUS_BACKUP_FINISHED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu sichernde Dateien werden ermittelt... ähnelt.
        /// </summary>
        internal static string STATUS_BACKUP_PREPARE {
            get {
                return ResourceManager.GetString("STATUS_BACKUP_PREPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang wird aufgrund von Fehlern abgebrochen... ähnelt.
        /// </summary>
        internal static string STATUS_CANCELLED_ERROR {
            get {
                return ResourceManager.GetString("STATUS_CANCELLED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang wird abgebrochen ähnelt.
        /// </summary>
        internal static string STATUS_CANCELLED_SHORT {
            get {
                return ResourceManager.GetString("STATUS_CANCELLED_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktueller Vorgang wird abgebrochen... ähnelt.
        /// </summary>
        internal static string STATUS_CANCELLED_TEXT {
            get {
                return ResourceManager.GetString("STATUS_CANCELLED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorbereiten... ähnelt.
        /// </summary>
        internal static string STATUS_PREPARE {
            get {
                return ResourceManager.GetString("STATUS_PREPARE", resourceCulture);
            }
        }
    }
}
