# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: AlexanderSeeligerSoftware.BackupServiceHome
PackageVersion: 3.9.3
InstallerType: inno
Scope: machine
MinimumOSVersion: 10.0.19045.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerUrl: https://download.brightbits.de/backupservicehome-3.9.3-win64.exe
  InstallerSha256: FF3000D9BFDCA9837FE6E486F426BEE73B5F8C1A4198718B38D17E146E9A5E57
ManifestType: installer
ManifestVersion: 1.9.0
