# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: AlexanderSeeligerSoftware.BackupServiceHome
PackageVersion: 3.9.3
PackageLocale: de-DE
Publisher: Alexander Seeliger Software
PublisherUrl: https://www.brightbits.de
PublisherSupportUrl: https://www.brightbits.de/help-und-support/backup-service-home/
PrivacyUrl: https://www.brightbits.de/datenschutz
Author: Alexander Seeliger
PackageName: Backup Service Home
PackageUrl: https://www.brightbits.de/produkte/backup-service-home/uebersicht/
License: Apache-2.0 license
LicenseUrl: https://github.com/alexsee/bsh3/blob/main/LICENSE
Copyright: Alexander Seeliger
ShortDescription: Backup Service Home 3 is a free, simple to use, and open source file backup software for Windows based on the Microsoft .NET Framework and written in C#.
Description: Backup Service Home 3 is a free, simple to use, and open source file backup software for Windows based on the Microsoft .NET Framework and written in C#.
Moniker: BackupServiceHome
ReleaseNotesUrl: https://www.brightbits.de/help-und-support/backup-service-home/kb2408041/
ManifestType: defaultLocale
ManifestVersion: 1.9.0
