name: Release stable version

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:

  release:
    runs-on: windows-latest
    
    env:
      Solution_Name: src\Backup Service Home 3.sln
      Test_Project_Path: src\BSH.Test\BSH.Test.csproj

    steps:

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release -p:RestorePackagesConfig=true
    
    - name: Build the application
      shell: powershell
      run: msbuild $env:Solution_Name /t:Rebuild /p:Configuration=Release

    - name: Building the installer
      run: |
        iscc.exe tools\setup\Setup.iss
      shell: cmd
    
    - name: Release to Github
      uses: softprops/action-gh-release@v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{runner.workspace}}/bsh3/tools/setup/output/backupservicehome-*.exe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: backup-service-home-setup
        path: ${{runner.workspace}}/bsh3/tools/setup/output/backupservicehome-*.exe
