name: Release stable version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
  workflow_dispatch:

jobs:

  release:
    runs-on: windows-latest
    
    env:
      Solution_Name: src\Backup Service Home 3.sln
      Test_Project_Path: src\BSH.Test\BSH.Test.csproj

    steps:
    - name: Set env
      run: |
        $version = "${{ github.ref_name }}".substring(1)
        echo "BUILD_VERSION=$version" >> $env:GITHUB_ENV

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build the application
      run: |
        dotnet publish -c Release -o ../output -a x64 --self-contained /p:Version=$env:BUILD_VERSION /p:FileVersion=$env:BUILD_VERSION
      working-directory: ./src

    - name: Building the installer
      run: |
        iscc.exe tools\setup\Setup.iss /DApplicationVersion=$env:BUILD_VERSION

    - name: Release to Github
      uses: softprops/action-gh-release@v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{runner.workspace}}/bsh3/tools/setup/output/backupservicehome-$BUILD_VERSION.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: backup-service-home-setup
        path: ${{runner.workspace}}/bsh3/tools/setup/output/backupservicehome-$BUILD_VERSION.exe
