name: Release stable version

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:

  release:
    runs-on: windows-latest
    environment: production
    
    env:
      Solution_Name: src\Backup Service Home 3.sln
      Test_Project_Path: src\BSH.Test\BSH.Test.csproj

    steps:

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release -p:RestorePackagesConfig=true
    
    - name: Build the application
      shell: powershell
      run: msbuild $env:Solution_Name /t:Rebuild /p:Configuration=Release

    - name: Building the installer
      run: |
        iscc.exe tools\setup\Setup.iss
      shell: cmd
    
    - name: Release to Github
      uses: softprops/action-gh-release@v0.1.13
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{runner.workspace}}/bsh3/tools/setup/output/backupservicehome-*.exe

    - name: Upload to Brightbits
      uses: mdallasanta/ssh-scp-deploy@v1
      with:
        local: ${{runner.workspace}}/bsh3/tools/setup/output/backupservicehome-*.exe
        remote: '~/'
        host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
        port: ${{secrets.REMOTE_PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
        user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
        key: ${{secrets.SSH_PRIVATE_KEY}}                                        # Remote server private key - REQUIRED at least one of "password" or "key" 
        ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        scp_options: -v                                              # Flags to use during scp - REQUIRED false - DEFAULT ''‚