name: Release stable version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:

  release:
    runs-on: windows-latest
    
    env:
      Solution_Name: src\Backup Service Home 3.sln
      Test_Project_Path: src\BSH.Test\BSH.Test.csproj

    steps:
    - name: Set env
      run: |
        $version = "${env:REF_NAME}".substring(1)
        $info_version = $version.replace('-beta', '.')
        echo "BUILD_VERSION=$version" >> $env:GITHUB_ENV
        echo "INFO_VERSION=$info_version" >> $env:GITHUB_ENV
      env:
        REF_NAME: ${{ github.ref_name }}

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.101

    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Build the application
      run: |
        dotnet publish -c Release -o ../output -a x64 --self-contained /p:Version=$env:BUILD_VERSION /p:FileVersion=$env:INFO_VERSION
        rm -R ../output/*.pdb
      working-directory: ./src

    - name: Building the installer
      run: |
        iscc.exe tools\setup\Setup.iss /DApplicationVersion=$env:BUILD_VERSION /DApplicationInfoVersion=$env:INFO_VERSION

    - name: Release to Github
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{runner.workspace}}/bsh3/tools/setup/output/backupservicehome-${{ env.BUILD_VERSION }}-win64.exe
