name: Build pull requests

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'tools/**'
      - '.github/**'

  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    environment: sonarcloud

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up JDK 17
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Setup dotnet
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
      with:
        dotnet-version: 10.0.300
        cache: true
        cache-dependency-path: src/**/packages.lock.json

    - name: Install SonarCloud scanner
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet tool install --global dotnet-coverage
    
    - name: Start sonarcloud scanner
      run: |
        dotnet sonarscanner begin /k:"alexsee_bsh3" /o:"alexsee" /d:sonar.token="$env:SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      working-directory: ./src

    - name: Restore dependencies
      run: dotnet restore "Backup Service Home 3.sln" --locked-mode -a x64
      working-directory: ./src

    - name: Build application
      run: |
        dotnet build "Backup Service Home 3.sln" --configuration Release --no-restore -p:Platform=x64
      working-directory: ./src

    - name: Test application and collect coverage
      run: |
        dotnet-coverage collect 'dotnet test "Backup Service Home 3.sln" --configuration Release --no-build --no-restore -p:Platform=x64' -f xml -o 'coverage.xml'
      working-directory: ./src

    - name: Finish the sonar cloud scanner
      run: dotnet sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      working-directory: ./src
